# @package _global_
data:
  train_path: data/an4_test_manifest.json
  val_path: data/an4_test_manifest.json
  batch_size: 32
  num_workers: 8
trainer:
  max_epochs: 20
  gpus: 0
  gradient_clip_val: 400  # Norm cutoff to prevent explosion of gradients
  plugins: ddp_sharded
  checkpoint_callback: True
checkpoint:
  save_top_k: 1
  monitor: "cer"
  verbose: True
  dirpath: model_an4_conv/
model:
  kernel_size: 5
  depth: 5
  algorithm: 'wav2letter'